apiVersion: v1
kind: Service
metadata:
  name: s2048
  labels:
    app: app2048
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: app2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d2048
  labels:
    app: app2048
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: app2048
  template:
    metadata:
      labels:
        app: app2048
    spec:
      containers:
        - name: c2048
          image: alexwhen/docker-2048
          imagePullPolicy: "Always"
          ports:
          - name: http
            containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: i2048
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: 2048.dreamit.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: s2048
                port: 
                  number: 80
